basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = "basic_app"

urlpatterns = [
    path("other", views.other, name="other"),
    path("relative", views.relative, name="relative"),
    path("register", views.register, name="register"),
    path("login", views.user_login, name="login"),
]

learning_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views as basic_app_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", basic_app_views.index, name="index"),
    path("basic_app/", include("basic_app.urls")),
    path("logout", basic_app_views.user_logout, name="logout"),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)
    # Create your models here.

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ("username", "email", "password")


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ("portfolio_site", "profile_pic")

basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm

from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout

# from basic_app.models import UserProfileInfo


# Create your views here.
def index(request):
    context_dict = {"number": 20, "text": "Hello World!"}
    return render(request, "basic_app/index.html", context_dict)


@login_required
def other(request):
    return render(request, "basic_app/other.html")


def relative(request):
    return render(request, "basic_app/relative_url_templates.html")


def register(request):
    registered = False

    if request.method == "POST":
        profile_form = UserProfileInfoForm(request.POST)
        user_form = UserForm(request.POST)
        if profile_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if "profile_pic" in request.FILES:
                profile.profile_pic = request.FILES["profile_pic"]

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(
        request,
        "basic_app/registration.html",
        context={
            "user_form": user_form,
            "profile_form": profile_form,
            "registered": registered,
        },
    )


def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse("index"))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed!")
            print(f"Username: {username} and password: {password}")
            return HttpResponse("Invalid login details!")

    return render(request, "basic_app/login.html", {})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href={% url "index" %}>Home</a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href={% url 'basic_app:other' %}>Other</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'basic_app:relative' %}>Relative</a> 
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'admin:index' %}>Admin</a> 
            </li>
            <li class="nav-item">
              <a class="nav-link" href={% url 'basic_app:register' %}>Register</a> 
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href={% url 'logout' %}>Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href={% url 'basic_app:login' %}>Login</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
        <!-- This is where the inherited html goes! -->
      {% endblock %}
    </div>
  </body>
</html>

templates/basic_app/index.html
<!DOCTYPE html> {% extends 'basic_app/base.html' %} {% block body_block %}

<h1>Welcome to the Homepage</h1>

<h2>This is the index page (homepage)</h2>

<h3>{{ text|cut:"Hello"|upper }}</h3>
<h3>{{ number|add:"90" }}</h3>
{% endblock body_block %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
<div class="container">
    <h1>Please login</h1>
    <form action="{% url 'basic_app:login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Enter Username">

        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Enter Password">

        <input type="submit" name="login" value="Login">
    </form>
</div>
{% endblock body_block %}

templates/basic_app/other.html
<!DOCTYPE html>
{% extends 'basic_app/base.html' %} {% block body_block %}
<h1>Welcome to Other</h1>
<h2>This is an example of template inheritance</h2>
{% endblock body_block %}

templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
<div class="container">
{% if registered %}
    <h1>Thank you for registering!</h1>
{% else %}
    <h1>Fill out the form:</h1>
    <form enctype="multipart/form-data", method="post" >
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p}}
        <input type="submit" class="btn btn-light" name="" value="Register"/>
    </form>
{% endif %}

</div>


{% endblock body_block %}

templates/basic_app/relative_url_templates.html
<!DOCTYPE html>

{% extends 'basic_app/base.html' %} {% block body_block %}
    <h1>Welcome to Relative URL Templates</h1>
    <h2>These are the links to different websites from the exercise</h2>
    <a href="{% url 'basic_app:other' %}">The other page </a><br />
    <a href="{% url 'admin:index' %}">The admin webpage</a>
    <a href="{% url 'index' %}">Link to index</a>
{% endblock  %}